GestContact/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GestContact.Models
{
    public class Contact
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public bool IsFavorite { get; set; }
    }
}

GestContact/Models/ErrorViewModel.cs
using System;

namespace GestContact.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GestContact/Controllers/ContactController.cs
using GestContact.Abstractions;
using GestContact.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GestContact.Controllers
{
    public class ContactController : Controller
    {
        public IContactService _service;

        public ContactController(IContactService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            List<Contact> contacts = _service.GetAll();
            return View(contacts);
        }
        [HttpPost]
        public IActionResult Index([FromForm]Contact cnt)
        {

            _service.AddContact(cnt);
            List<Contact> contacts = _service.GetAll();
            return View(contacts);
        }
        public RedirectToActionResult RemoveContact(int id)
        {
            _service.RemoveContact(id);
            return RedirectToAction("Index");
        }
        
        
    }
}

GestContact/Controllers/HomeController.cs
using GestContact.Abstractions;
using GestContact.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GestContact.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly IContactService _contactService;

        public HomeController(
            ILogger<HomeController> logger, 
            IContactService contactService
        )
        {
            _logger = logger;
            _contactService = contactService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GestContact/Views/Contact/Index.cshtml
@model List<Contact>

@*<a asp-action="TabContact" asp-controller="Contact" class="btn btn-dark" type="submit">Ajouter</a>*@
<button class="btn btn-dark" data-toggle="modal" data-target="#exampleModal">Ajouter</button>
<table class="table ">
    <tr>
        <td>Nom</td>
        <td>Prenom</td>
        <td>Favori</td>
        <td>Action</td>
    </tr>
    @if (Model != null)
    {
        @foreach (Contact item in Model)
        {
            <tr>
                <td>@item.LastName</td>
                <td>@item.FirstName</td>
                <td>@(item.IsFavorite ? "♥" : "X")</td>
                <td><span>
                        
                        <a asp-controller="Contact" asp-action="RemoveContact" asp-route-id="@item.Id" >Delete</a>
                        <a>action</a>
                    </span>
                </td>
            </tr>

        }
    }
</table>
@{ 
    Contact ok = new Contact();
}
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form class=" form" asp-action="Index" asp-controller="Contact" method="post">

                    <input name="FirstName" value="Prénom" class=" form-control" type="text" />
                    <input name="LastName" value="Nom" class=" form-control" type="text" />
                    <input name="Email" value="Email" class=" form-control" type="text" />
                    <input type="submit"  value="Add" class="btn btn-primary" />
                    
                </form>
            </div>
            
        </div>
    </div>
</div>

GestContact/Views/Contact/TabContact.cshtml
@model GestContact.Models.Contact

@{
    ViewData["Title"] = "View";
}



<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index" asp-controller="Contact" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">

                <input asp-for="FirstName" value="Prénom" class=" form-control" type="text" />
                <input asp-for="LastName" value="Nom" class=" form-control" type="text" />
                <input asp-for="Email" value="Email" class=" form-control" type="text" />
                <span>
                    <label>Favori ?</label>
                    <input type="checkbox" asp-for="IsFavorite" />
                </span>
                

                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestContact/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GestContact/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestContact</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GestContact</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GestContact - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>